# Generated by Django 3.2 on 2021-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emailid', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Subject', models.CharField(max_length=30)),
                ('Message', models.TextField()),
                ('organisation_isapproved', models.CharField(choices=[('Stocks', 'Stocks'), ('Cryptocurrency', 'Cryptocurrency')], default='Stocks', max_length=20)),
            ],
        ),
    ]
