# Generated by Django 3.2 on 2021-04-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='organisation_isapproved',
            new_name='Selected_Course',
        ),
    ]
