# Generated by Django 3.2 on 2021-04-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_organisation_isapproved_contactus_selected_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='Subject',
        ),
    ]
