# Generated by Django 3.2 on 2021-05-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_watchstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertquestions',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='expertquestions',
            name='answerdate',
        ),
        migrations.RemoveField(
            model_name='expertquestions',
            name='expert_email',
        ),
        migrations.RemoveField(
            model_name='expertquestions',
            name='questionTitle',
        ),
        migrations.RemoveField(
            model_name='expertquestions',
            name='questiondate',
        ),
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
