# Generated by Django 3.2 on 2021-05-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210527_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockguide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200)),
                ('answers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
