# Generated by Django 3.2 on 2021-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cryptoguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoguide',
            name='pdf',
            field=models.FileField(blank=True, upload_to='data'),
        ),
        migrations.AddField(
            model_name='cryptoguide',
            name='picture',
            field=models.ImageField(blank=True, upload_to='data'),
        ),
    ]
